# Generated by Django 4.2.24 on 2025-09-30 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("budgets", "0018_alter_budgetheader_budget_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                ("audit_trail_ID", models.AutoField(primary_key=True, serialize=False)),
                ("action_time", models.DateField()),
                ("action_description", models.CharField(max_length=500)),
                (
                    "budget_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgets.budgetheader",
                    ),
                ),
            ],
        ),
    ]
