# Generated by Django 4.2.24 on 2025-09-30 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budgets", "0019_alter_budgetheader_budget_created_at"),
        ("auditTrails", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditTrails",
            fields=[
                ("audit_trail_ID", models.AutoField(primary_key=True, serialize=False)),
                ("action_time", models.DateField()),
                ("action_description", models.CharField(max_length=500)),
                (
                    "action_doer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "budget_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgets.budgetheader",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AuditTrail",
        ),
    ]
