# Generated by Django 4.2 on 2025-08-16 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetHeader",
            fields=[
                ("budget_ID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "month",
                    models.CharField(
                        choices=[
                            ("January", "January"),
                            ("February", "February"),
                            ("March", "March"),
                            ("April", "April"),
                            ("May", "May"),
                            ("June", "June"),
                        ],
                        max_length=15,
                    ),
                ),
                ("budget_created_at", models.DateField(blank=True, null=True)),
                ("monthly_budget_available", models.FloatField()),
                (
                    "budget_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "budget headers",
            },
        ),
        migrations.CreateModel(
            name="BudgetLines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(50)),
                ("item_quantity", models.IntegerField()),
                (
                    "is_recurrent",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "budgetHeader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="budgets.budgetheader",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "budget lines",
            },
        ),
    ]
