# Generated by Django 4.2 on 2025-08-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetlines",
            name="item_price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
