# Generated by Django 4.2 on 2025-09-14 16:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budgets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetheader",
            name="budget_month",
            field=models.CharField(
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                default="April",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="budgetheader",
            name="budget_year",
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name="budgetlines",
            name="item_category",
            field=models.CharField(
                choices=[
                    ("Health", "Health"),
                    ("Debt payments", "Debt payments"),
                    ("Rent / mortgage", "Rent / mortgage"),
                    ("Energy", "Energy"),
                    ("Groceries", "Groceries"),
                    ("Transport", "Transport"),
                    ("Gym", "Gym"),
                    ("Eating out", "Eating out"),
                    ("Entertainment", "Entertainment"),
                    ("Other", "Other"),
                ],
                default=django.utils.timezone.now,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="budgetlines",
            name="item_notes",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="budgetlines",
            name="item_price",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="budgetheader",
            name="budget_created_at",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2025, 9, 14, 16, 4, 12, 613943, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="budgetheader",
            name="budget_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="budgetlines",
            name="item_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="budgetheader",
            unique_together={("budget_month", "budget_year")},
        ),
        migrations.RemoveField(
            model_name="budgetheader",
            name="month",
        ),
    ]
