# Generated by Django 4.2 on 2025-08-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0002_budgetlines_item_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="budgetheader",
            old_name="month",
            new_name="budget_month",
        ),
    ]
