# Generated by Django 4.2 on 2025-09-14 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0003_alter_budgetheader_budget_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetheader",
            name="budget_created_at",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2025, 9, 14, 19, 18, 14, 344368, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="budgetheader",
            name="budget_month",
            field=models.CharField(
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                default="April",
                max_length=15,
            ),
        ),
    ]
