# Generated by Django 4.2 on 2025-08-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0003_rename_month_budgetheader_budget_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetheader",
            name="budget_month",
            field=models.CharField(
                choices=[
                    ("January", "January"),
                    ("February", "February"),
                    ("March", "March"),
                    ("April", "April"),
                    ("May", "May"),
                    ("June", "June"),
                    ("July", "July"),
                    ("August", "August"),
                    ("September", "September"),
                    ("October", "October"),
                    ("November", "November"),
                    ("December", "December"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="budgetlines",
            name="item_price",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
