# Generated by Django 4.2 on 2025-08-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0004_alter_budgetheader_budget_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetheader",
            name="budget_year",
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
    ]
