# Generated by Django 4.2 on 2025-09-14 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0004_alter_budgetheader_budget_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetheader",
            name="budget_created_at",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2025, 9, 14, 19, 21, 9, 359198, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
