# Generated by Django 4.2 on 2025-09-14 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0005_alter_budgetheader_budget_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetheader",
            name="budget_created_at",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2025, 9, 14, 19, 22, 45, 784923, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
