# Generated by Django 4.2 on 2025-08-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0005_budgetheader_budget_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetlines",
            name="item_category",
            field=models.CharField(
                choices=[
                    ("Health", "Health"),
                    ("Debt payments", "Debt payments"),
                    ("Rent / mortgage", "Rent / mortgage"),
                    ("Groceries", "Groceries"),
                    ("Transport", "Transport"),
                    ("Eating out", "Eating out"),
                    ("Entertainment", "Entertainment"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="budgetlines",
            name="item_notes",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="budgetlines",
            name="item_name",
            field=models.CharField(max_length=50),
        ),
    ]
