# Generated by Django 4.2 on 2025-09-14 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0006_alter_budgetheader_budget_created_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="budgetheader",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="budgetheader",
            name="budget_created_at",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2025, 9, 14, 19, 24, 8, 397783, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
