# Generated by Django 4.2 on 2025-08-17 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0006_budgetlines_item_category_budgetlines_item_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetheader",
            name="budget_created_at",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2025, 8, 17, 15, 25, 53, 160532, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
