# Generated by Django 4.2.24 on 2025-09-21 17:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0009_alter_budgetheader_budget_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetheader",
            name="original_owner",
            field=models.CharField(
                blank=True,
                default=models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL,
                ),
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="budgetheader",
            name="budget_created_at",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2025, 9, 21, 17, 21, 39, 863394, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="budgetheader",
            unique_together={("budget_month", "budget_year")},
        ),
    ]
