# Generated by Django 4.2.24 on 2025-09-21 17:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budgets", "0010_budgetheader_original_owner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budgetheader",
            name="original_owner",
        ),
        migrations.AddField(
            model_name="budgetheader",
            name="original_budget_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="original_budgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="budgetheader",
            name="budget_created_at",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2025, 9, 21, 17, 34, 51, 191222, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="budgetheader",
            name="budget_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_budgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
