# Generated by Django 4.2.24 on 2025-09-27 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0012_alter_budgetheader_budget_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetheader",
            name="budget_created_at",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2025, 9, 27, 10, 7, 54, 653177, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
