# Generated by Django 4.2.24 on 2025-09-27 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0013_alter_budgetheader_budget_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetheader",
            name="budget_created_at",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2025, 9, 27, 10, 9, 47, 642809, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="budgetlines",
            name="item_category",
            field=models.CharField(
                choices=[
                    ("Health", "Health"),
                    ("Debt payments", "Debt payments"),
                    ("Rent / mortgage", "Rent / mortgage"),
                    ("Energy", "Energy"),
                    ("Groceries", "Groceries"),
                    ("Transport", "Transport"),
                    ("Gym", "Gym"),
                    ("Eating out", "Eating out"),
                    ("Entertainment", "Entertainment"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
