# Generated by Django 4.2.24 on 2025-09-27 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0015_alter_budgetheader_budget_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetheader",
            name="budget_created_at",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2025, 9, 27, 12, 51, 0, 198192, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
