# Generated by Django 4.2.24 on 2025-09-30 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0018_alter_budgetheader_budget_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetheader",
            name="budget_created_at",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2025, 9, 30, 17, 45, 6, 273182, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
