# Generated by Django 4.2.24 on 2025-09-21 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "notification_ID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "notification_text",
                    models.CharField(
                        choices=[
                            ("Welcome to the app!", "Welcome to the app!"),
                            (
                                "A user has sent you one budget",
                                "A user has sent you one budget",
                            ),
                        ],
                        max_length=500,
                    ),
                ),
                ("notification_time", models.TimeField()),
                (
                    "notification_viewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
