# Generated by Django 4.2.24 on 2025-09-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="notification_text",
            field=models.CharField(max_length=500),
        ),
    ]
