# Generated by Django 4.2.24 on 2025-09-22 21:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notifications_notification_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="notification_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
